package:
    name: rfsc
    version: '1.0.0'

source:
    path: ..
requirements:
    build:
        - gxx_linux-64
        - cmake
        - python
        - pip
dependencies:
    - pip
    - pip:
            - wheel
            - pandas
            - numpy
            - sklearn
            - keras
            - tensorflow
            - xgboost
about:
    home: https://github.com/cobilab/RFSC
    license: GPL v3 License
    license_family: GPL
    summary: Reference-Free Sequence Classification Tool for DNA sequences in metagenomic samples
